/* A List of the best possible moves, in it's own file to declutter the main file */

export type MoveDict = { [from: string]: { [to: string]: string[] } };

export enum Key {
  ZERO = '0',
  ONE = '1',
  TWO = '2',
  THREE = '3',
  FOUR = '4',
  FIVE = '5',
  SIX = '6',
  SEVEN = '7',
  EIGHT = '8',
  NINE = '9',
  UP = '^',
  RIGHT = '>',
  DOWN = 'v',
  LEFT = '<',
  ENTER = 'A',
}

export const KEYPAD_MOVES: MoveDict = {
  [Key.ENTER]: {
    [Key.ENTER]: ['A'],
    [Key.ZERO]: ['<A'],
    [Key.ONE]: ['^<<A'],
    [Key.TWO]: ['^<A', '<^A'],
    [Key.THREE]: ['^A'],
    [Key.FOUR]: ['^^<<A'],
    [Key.FIVE]: ['<^^A', '^^<A'],
    [Key.SIX]: ['^^A'],
    [Key.SEVEN]: ['^^^<<'],
    [Key.EIGHT]: ['^^^<A', '<^^^A'],
    [Key.NINE]: ['^^^A'],
  },
  [Key.ZERO]: {
    [Key.ENTER]: ['>A'],
    [Key.ZERO]: ['A'],
    [Key.ONE]: ['^<A'],
    [Key.TWO]: ['^A'],
    [Key.THREE]: ['^>A', '>^A'],
    [Key.FOUR]: ['^^<A', '^<^A'],
    [Key.FIVE]: ['^^A'],
    [Key.SIX]: ['^^>A', '>^^A'],
    [Key.SEVEN]: ['^^^<A'],
    [Key.EIGHT]: ['^^^A'],
    [Key.NINE]: ['^^^>A', '>^^^A'],
  },
  [Key.ONE]: {
    [Key.ENTER]: ['>>vA'],
    [Key.ZERO]: ['>vA'],
    [Key.ONE]: ['A'],
    [Key.TWO]: ['>A'],
    [Key.THREE]: ['>>A'],
    [Key.FOUR]: ['^A'],
    [Key.FIVE]: ['^>A', '>^A'],
    [Key.SIX]: ['^>>A', '>>^A'],
    [Key.SEVEN]: ['^^A'],
    [Key.EIGHT]: ['^^>A', '>^^A'],
    [Key.NINE]: ['^^>>A', '>>^^A'],
  },
  [Key.TWO]: {
    [Key.ENTER]: ['>vA', 'v>A'],
    [Key.ZERO]: ['vA'],
    [Key.ONE]: ['<A'],
    [Key.TWO]: ['A'],
    [Key.THREE]: ['>A'],
    [Key.FOUR]: ['^<A', '<^A'],
    [Key.FIVE]: ['^A'],
    [Key.SIX]: ['^>A', '>^A'],
    [Key.SEVEN]: ['^^<A', '<^^A'],
    [Key.EIGHT]: ['^^A'],
    [Key.NINE]: ['^^>A', '>^^A'],
  },
  [Key.THREE]: {
    [Key.ENTER]: ['vA'],
    [Key.ZERO]: ['v<A', 'v<A'],
    [Key.ONE]: ['<<A'],
    [Key.TWO]: ['<A'],
    [Key.THREE]: ['A'],
    [Key.FOUR]: ['^<<A', '<<^A'],
    [Key.FIVE]: ['^<A', '<^A'],
    [Key.SIX]: ['^A'],
    [Key.SEVEN]: ['<<^^A', '^^<<A'],
    [Key.EIGHT]: ['^^<A', '<^^A'],
    [Key.NINE]: ['^^A'],
  },
  [Key.FOUR]: {
    [Key.ENTER]: ['>>vvA'],
    [Key.ZERO]: ['>vvA'],
    [Key.ONE]: ['vA'],
    [Key.TWO]: ['>vA', 'v>A'],
    [Key.THREE]: ['v>>A', '>>vA'],
    [Key.FOUR]: ['A'],
    [Key.FIVE]: ['>A'],
    [Key.SIX]: ['>>A'],
    [Key.SEVEN]: ['^A'],
    [Key.EIGHT]: ['^>A', '>^A'],
    [Key.NINE]: ['^>>A', '>>^A'],
  },
  [Key.FIVE]: {
    [Key.ENTER]: ['>vvA', 'vv>A'],
    [Key.ZERO]: ['vvA'],
    [Key.ONE]: ['v<A', '<vA'],
    [Key.TWO]: ['vA'],
    [Key.THREE]: ['v>A', '>vA'],
    [Key.FOUR]: ['<A'],
    [Key.FIVE]: ['A'],
    [Key.SIX]: ['>A'],
    [Key.SEVEN]: ['^<A', '<^A'],
    [Key.EIGHT]: ['^A'],
    [Key.NINE]: ['^>A', '>^A'],
  },
  [Key.SIX]: {
    [Key.ENTER]: ['vvA'],
    [Key.ZERO]: ['vv<A', '<vvA'],
    [Key.ONE]: ['v<<A', '<<v'],
    [Key.TWO]: ['v<A', '<vA'],
    [Key.THREE]: ['vA'],
    [Key.FOUR]: ['<<A'],
    [Key.FIVE]: ['<A'],
    [Key.SIX]: ['A'],
    [Key.SEVEN]: ['^<<A', '<<^A'],
    [Key.EIGHT]: ['^<A', '^<A'],
    [Key.NINE]: ['^A'],
  },
  [Key.SEVEN]: {
    [Key.ENTER]: ['>>vvvA'],
    [Key.ZERO]: ['>vvvA'],
    [Key.ONE]: ['vvA'],
    [Key.TWO]: ['vv>A', '>vvA'],
    [Key.THREE]: ['vv>>A', '>>vvA'],
    [Key.FOUR]: ['vA'],
    [Key.FIVE]: ['v>A', '>vA'],
    [Key.SIX]: ['v>>A', '>>vA'],
    [Key.SEVEN]: ['A'],
    [Key.EIGHT]: ['>A'],
    [Key.NINE]: ['>>A'],
  },
  [Key.EIGHT]: {
    [Key.ENTER]: ['vvv>A', '>vvvA'],
    [Key.ZERO]: ['vvvA'],
    [Key.ONE]: ['vv<A', '<vvA'],
    [Key.TWO]: ['vvA'],
    [Key.THREE]: ['vv>A', '>vvA'],
    [Key.FOUR]: ['v<A', '<vA'],
    [Key.FIVE]: ['vA'],
    [Key.SIX]: ['v>A', '>vA'],
    [Key.SEVEN]: ['<A'],
    [Key.EIGHT]: ['A'],
    [Key.NINE]: ['>A'],
  },
  [Key.NINE]: {
    [Key.ENTER]: ['vvvA'],
    [Key.ZERO]: ['vvv<A', '<vvvA'],
    [Key.ONE]: ['vv<<A', '<<vvA'],
    [Key.TWO]: ['vv<A', '<vvA'],
    [Key.THREE]: ['vvA'],
    [Key.FOUR]: ['v<<A', '<<vA'],
    [Key.FIVE]: ['v<A', '<vA'],
    [Key.SIX]: ['vA'],
    [Key.SEVEN]: ['<<A'],
    [Key.EIGHT]: ['<A'],
    [Key.NINE]: ['A'],
  },
};

export const ARROWS_MOVES: MoveDict = {
  [Key.ENTER]: {
    [Key.ENTER]: ['A'],
    [Key.UP]: ['<A'],
    [Key.RIGHT]: ['vA'],
    [Key.DOWN]: ['<vA', 'v<A'],
    [Key.LEFT]: ['v<<A', '<v<A'],
  },
  [Key.UP]: {
    [Key.ENTER]: ['>A'],
    [Key.UP]: ['A'],
    [Key.RIGHT]: ['v>A', '>vA'],
    [Key.DOWN]: ['vA'],
    [Key.LEFT]: ['v<A'],
  },
  [Key.RIGHT]: {
    [Key.ENTER]: ['^A'],
    [Key.UP]: ['<^A', '^<A'],
    [Key.RIGHT]: ['A'],
    [Key.DOWN]: ['<A'],
    [Key.LEFT]: ['<<A'],
  },
  [Key.DOWN]: {
    [Key.ENTER]: ['^>A', '>^A'],
    [Key.UP]: ['^A'],
    [Key.RIGHT]: ['>A'],
    [Key.DOWN]: ['A'],
    [Key.LEFT]: ['<A'],
  },
  [Key.LEFT]: {
    [Key.ENTER]: ['>>^A', '>^>A'],
    [Key.UP]: ['>^A'],
    [Key.RIGHT]: ['>>A'],
    [Key.DOWN]: ['>A'],
    [Key.LEFT]: ['A'],
  },
};
